//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Serialization;

    [DataContract]
    [KnownType(typeof(Author))]
    [KnownType(typeof(Book))]
    [KnownType(typeof(BookAuthor))]
    [KnownType(typeof(BookCover))]
    [KnownType(typeof(BookSubject))]
    [KnownType(typeof(sysdiagrams))]
    [KnownType(typeof(DbSet<Author>))]
    [KnownType(typeof(DbSet<Book>))]
    [KnownType(typeof(DbSet<BookAuthor>))]
    [KnownType(typeof(DbSet<BookCover>))]
    [KnownType(typeof(DbSet<BookSubject>))]
    [KnownType(typeof(DbSet<sysdiagrams>))]
    public partial class BookManagerDbEntities : DbContext
    {
        public BookManagerDbEntities()
            : base("name=BookManagerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [DataMember]
        public virtual DbSet<Author> Author { get; set; }
        [DataMember]
        public virtual DbSet<Book> Book { get; set; }
        [DataMember]
        public virtual DbSet<BookAuthor> BookAuthor { get; set; }
        [DataMember]
        public virtual DbSet<BookCover> BookCover { get; set; }
        [DataMember]
        public virtual DbSet<BookSubject> BookSubject { get; set; }
        [DataMember]
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
